In [1]:
%cd ..

D:\SoftUni\Data Science\7. Data science project architecture\07.Lab

In [2]:
import pandas as pd
from src import functions

In [3]:
asthma_data = pd.read_csv('data/asthma_disease_data.csv')

### Columns names

In [4]:
asthma_data.columns

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'LungFunctionFEV1', 'LungFunctionFVC',
       'Wheezing', 'ShortnessOfBreath', 'ChestTightness', 'Coughing',
       'NighttimeSymptoms', 'ExerciseInduced', 'Diagnosis', 'DoctorInCharge'],
      dtype='object')

All columns names are Pascal cased. Snake case will be more appropriate here.

In [5]:
asthma_data.rename(functions.to_snake_case, axis = 'columns', inplace = True)

In [6]:
asthma_data.columns

Index(['patient_id', 'age', 'gender', 'ethnicity', 'education_level', 'bmi',
       'smoking', 'physical_activity', 'diet_quality', 'sleep_quality',
       'pollution_exposure', 'pollen_exposure', 'dust_exposure', 'pet_allergy',
       'family_history_asthma', 'history_of_allergies', 'eczema', 'hay_fever',
       'gastroesophageal_reflux', 'lung_function_fev1', 'lung_function_fvc',
       'wheezing', 'shortness_of_breath', 'chest_tightness', 'coughing',
       'nighttime_symptoms', 'exercise_induced', 'diagnosis',
       'doctor_in_charge'],
      dtype='object')

### Rounding
For better readability, I round the floats to the second decimal place.

In [7]:
asthma_data = asthma_data.round(2)

In [8]:
asthma_data.sample(5)

,patient_id,age,gender,ethnicity,education_level,bmi,smoking,physical_activity,diet_quality,sleep_quality,...,lung_function_fev1,lung_function_fvc,wheezing,shortness_of_breath,chest_tightness,coughing,nighttime_symptoms,exercise_induced,diagnosis,doctor_in_charge
1995,7029,68,1,0,3,30.71,0,8.02,4.14,9.57,...,3.78,4.15,0,1,1,0,0,0,0,Dr_Confid
56,5090,58,0,0,1,15.64,0,2.94,9.88,9.44,...,3.88,2.25,1,1,1,1,1,0,0,Dr_Confid
1096,6130,53,1,0,1,18.01,0,3.63,6.78,8.01,...,3.16,1.83,1,1,0,0,0,1,0,Dr_Confid
16,5050,7,1,0,1,31.70,1,8.19,0.62,4.19,...,1.00,3.86,0,0,1,1,0,1,0,Dr_Confid
191,5225,18,1,0,0,30.18,0,8.19,6.26,5.05,...,2.08,2.72,1,0,0,0,1,1,0,Dr_Confid

### Doctor in charge

This column has only one unique value for all observations. It is because the information is confidential. Since this column has no real value for the analysis, it is safe to delete it.

In [9]:
asthma_data.drop(columns = ['doctor_in_charge'], inplace = True)

In [10]:
asthma_data.sample(5)

,patient_id,age,gender,ethnicity,education_level,bmi,smoking,physical_activity,diet_quality,sleep_quality,...,gastroesophageal_reflux,lung_function_fev1,lung_function_fvc,wheezing,shortness_of_breath,chest_tightness,coughing,nighttime_symptoms,exercise_induced,diagnosis
1687,6721,21,0,1,1,37.58,0,3.06,2.33,6.56,...,0,3.73,4.30,0,0,1,1,1,0,0
2170,7204,48,1,0,1,39.17,1,0.40,9.51,5.67,...,1,1.65,1.66,1,1,0,1,1,0,1
2231,7265,6,1,0,2,22.63,0,1.26,2.24,4.62,...,1,1.45,3.38,1,1,1,1,1,0,0
937,5971,74,1,0,0,15.73,0,0.69,8.73,6.02,...,0,1.25,5.96,1,0,0,0,0,0,0
1567,6601,32,1,0,1,30.15,0,0.41,8.02,7.41,...,0,1.99,2.94,0,1,1,1,1,1,0