In [1]:
%cd ..

D:\SoftUni\Data Science\7. Data science project architecture\07.Lab

In [2]:
import pandas as pd
from src import functions

In [17]:
asthma_data = pd.read_csv('data/asthma_disease_data.csv')

### Columns names

In [18]:
asthma_data.columns

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'LungFunctionFEV1', 'LungFunctionFVC',
       'Wheezing', 'ShortnessOfBreath', 'ChestTightness', 'Coughing',
       'NighttimeSymptoms', 'ExerciseInduced', 'Diagnosis', 'DoctorInCharge'],
      dtype='object')

All columns names are Pascal cased. Snake case will be more appropriate here.

In [19]:
asthma_data.rename(functions.to_snake_case, axis = 'columns', inplace = True)

In [20]:
asthma_data.columns

Index(['patient_id', 'age', 'gender', 'ethnicity', 'education_level', 'bmi',
       'smoking', 'physical_activity', 'diet_quality', 'sleep_quality',
       'pollution_exposure', 'pollen_exposure', 'dust_exposure', 'pet_allergy',
       'family_history_asthma', 'history_of_allergies', 'eczema', 'hay_fever',
       'gastroesophageal_reflux', 'lung_function_fev1', 'lung_function_fvc',
       'wheezing', 'shortness_of_breath', 'chest_tightness', 'coughing',
       'nighttime_symptoms', 'exercise_induced', 'diagnosis',
       'doctor_in_charge'],
      dtype='object')

### Rounding
For better readability, I round the floats to the second decimal place.

In [21]:
asthma_data = asthma_data.round(2)

In [22]:
asthma_data.sample(5)

,patient_id,age,gender,ethnicity,education_level,bmi,smoking,physical_activity,diet_quality,sleep_quality,...,lung_function_fev1,lung_function_fvc,wheezing,shortness_of_breath,chest_tightness,coughing,nighttime_symptoms,exercise_induced,diagnosis,doctor_in_charge
1818,6852,43,1,1,0,31.58,0,5.94,4.09,9.37,...,1.76,4.24,1,0,0,1,0,0,0,Dr_Confid
101,5135,28,1,0,2,18.16,0,0.67,8.65,7.82,...,1.44,1.86,1,0,1,0,1,0,0,Dr_Confid
2089,7123,31,1,0,1,36.95,0,5.90,0.66,5.29,...,1.45,3.21,1,0,0,0,0,0,0,Dr_Confid
1501,6535,19,0,2,0,33.44,0,6.12,7.35,8.29,...,3.35,5.33,1,1,1,1,0,0,0,Dr_Confid
1131,6165,51,1,1,1,32.72,0,4.94,2.36,5.37,...,2.63,3.11,1,0,1,0,0,1,0,Dr_Confid

### Doctor in charge

This column has only one unique value for all observations. It is because the information is confidential. Since this column has no real value for the analysis, it is safe to delete it.

In [23]:
asthma_data.drop(columns = ['doctor_in_charge'], inplace = True)

In [24]:
asthma_data.sample(5)

,patient_id,age,gender,ethnicity,education_level,bmi,smoking,physical_activity,diet_quality,sleep_quality,...,gastroesophageal_reflux,lung_function_fev1,lung_function_fvc,wheezing,shortness_of_breath,chest_tightness,coughing,nighttime_symptoms,exercise_induced,diagnosis
689,5723,36,0,1,0,36.03,0,1.89,5.95,6.95,...,0,2.23,5.06,1,1,0,0,0,1,0
1469,6503,32,0,0,0,16.81,0,3.01,7.15,6.60,...,0,2.82,3.54,0,0,1,1,1,0,0
2132,7166,72,0,0,1,36.95,0,0.70,4.43,6.03,...,0,1.84,2.08,0,0,0,0,1,0,0
248,5282,67,0,0,1,21.06,0,8.24,9.01,7.70,...,0,2.28,1.70,1,0,0,1,0,1,0
2127,7161,39,1,0,2,24.74,0,7.66,6.52,4.04,...,0,2.41,2.82,0,1,0,0,1,1,0

### Patient id

Since all observations are indexed by Pandas, there are two index columns. Dropping 'patient_id' column and leave indexes starting from zero.

In [25]:
asthma_data.drop(columns = ['patient_id'], inplace = True)

In [29]:
asthma_data.sample(2)

,age,gender,ethnicity,education_level,bmi,smoking,physical_activity,diet_quality,sleep_quality,pollution_exposure,...,gastroesophageal_reflux,lung_function_fev1,lung_function_fvc,wheezing,shortness_of_breath,chest_tightness,coughing,nighttime_symptoms,exercise_induced,diagnosis
497,58,1,1,0,26.45,0,3.10,5.39,8.81,9.59,...,0,2.84,5.96,0,1,1,1,0,1,0
1937,64,0,0,0,22.34,0,7.33,7.57,9.14,2.65,...,1,1.24,1.85,0,1,1,1,1,0,0

In [ ]:
asthma_data_cleaned = pd.

In [35]:
# Save a copy of cleaned dataframe for further exploration to 'data/asthma_data_cleaned.csv'
asthma_data.to_csv('data/asthma_data_cleaned.csv', index=False)